
hmpps.sqs:
  provider: localstack
  localstackUrl: http://localhost:4666
  queues:
    domaineventsqueue:
      queueName: domainevents-queue
      dlqName: domainevents-queue-dlq
      subscribeTopicId: domainevents
  topics:
    domainevents:
      arn: arn:aws:sns:eu-west-2:000000000000:domainevents-topic

