package uk.gov.justice.digital.hmpps.hmppshdcapi.licences.conditions

// NOTE: DO NOT EDIT DIRECTLY: This is generated via "npm run generate:kotlin-types" in https://github.com/ministryofjustice/licences
 
val V1_CONDITIONS = listOf(
  ConditionMetadata(
    id = "NOCONTACTPRISONER",
    text = "Not to contact directly or indirectly any person who is a serving or remand offender or detained in State custody, without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "People, contact and relationships",
    subgroupName = "Person or group",
  ),
  ConditionMetadata(
    id = "NOCONTACTASSOCIATE",
    text = "Not to associate with any person currently or formerly associated with [NAME OR DESCRIBE SPECIFIC GROUPS OR ORGANISATIONS] without the prior approval of your supervising officer.",
    userInput = "groupsOrOrganisations",
    fieldPosition = mapOf("groupsOrOrganisation" to 0),
    groupName = "People, contact and relationships",
    subgroupName = "Person or group",
  ),
  ConditionMetadata(
    id = "NOCONTACTSEXOFFENDER",
    text = "Not to contact or associate with a known sex offender other than when compelled by attendance at a Treatment Programme or when residing at Approved Premises without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "People, contact and relationships",
    subgroupName = "Person or group",
  ),
  ConditionMetadata(
    id = "INTIMATERELATIONSHIP",
    text = "Notify your supervising officer of any developing intimate relationships with [WOMEN / MEN / WOMEN OR MEN].",
    userInput = "intimateGender",
    fieldPosition = mapOf("intimateGender" to 0),
    groupName = "People, contact and relationships",
    subgroupName = "Person or group",
  ),
  ConditionMetadata(
    id = "NOCONTACTNAMED",
    text = "Not to contact or associate with [NAMED OFFENDER(S) / NAMED INDIVIDUAL(S)] without the prior approval of your supervising officer.",
    userInput = "noContactOffenders",
    fieldPosition = mapOf("noContactOffenders" to 0),
    groupName = "People, contact and relationships",
    subgroupName = "Person or group",
  ),
  ConditionMetadata(
    id = "NORESIDE",
    text = "Not to reside (not even to stay for one night) in the same household as [ANY / ANY FEMALE / ANY MALE] child under the age of [INSERT AGE] without the prior approval of your supervising officer.",
    userInput = "notToReside",
    fieldPosition = mapOf("notResideWithAge" to 1, "notResideWithGender" to 0),
    groupName = "People, contact and relationships",
    subgroupName = "Children",
  ),
  ConditionMetadata(
    id = "NOUNSUPERVISEDCONTACT",
    text = "Not to have unsupervised contact with  [ANY / ANY FEMALE / ANY MALE] children under the age of [INSERT AGE] without the prior approval of your supervising officer and / or [INSERT NAME OF APPROPRIATE SOCIAL SERVICES DEPARTMENT] except where that contact is inadvertent and not reasonably avoidable in the course of lawful daily life.",
    userInput = "noUnsupervisedContact",
    fieldPosition = mapOf("unsupervisedContactAge" to 1, "unsupervisedContactGender" to 0, "unsupervisedContactSocial" to 2),
    groupName = "People, contact and relationships",
    subgroupName = "Children",
  ),
  ConditionMetadata(
    id = "NOCHILDRENSAREA",
    text = "Not to enter or remain in sight of any [CHILDREN’S PLAY AREA, SWIMMING BATHS, SCHOOL ETC] without the prior approval of your supervising officer.",
    userInput = "notInSightOf",
    fieldPosition = mapOf("notInSightOf" to 0),
    groupName = "People, contact and relationships",
    subgroupName = "Children",
  ),
  ConditionMetadata(
    id = "NOWORKWITHAGE",
    text = "Not to undertake work or other organised activity which will involve a person under the age of [INSERT AGE], either on a paid or unpaid basis without the prior approval of your supervising officer.",
    userInput = "noWorkWithAge",
    fieldPosition = mapOf("noWorkWithAge" to 0),
    groupName = "People, contact and relationships",
    subgroupName = "Children",
  ),
  ConditionMetadata(
    id = "NOTIFYRELATIONSHIP",
    text = "Notify your supervising officer of any developing personal relationships, whether intimate or not, with any person you know or believe to be resident in a household containing children under the age of 18. This includes persons known to you prior to your time in custody with whom you are renewing or developing a personal relationship with.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "People, contact and relationships",
    subgroupName = "Children",
  ),
  ConditionMetadata(
    id = "NOCOMMUNICATEVICTIM",
    text = "Not to seek to approach or communicate with [INSERT NAME OF VICTIM AND / OR FAMILY MEMBERS] without the prior approval of your supervising officer and / or [INSERT NAME OF APPROPRIATE SOCIAL SERVICES DEPARTMENT].",
    userInput = "victimDetails",
    fieldPosition = mapOf("socialServicesDept" to 1, "victimFamilyMembers" to 0),
    groupName = "People, contact and relationships",
    subgroupName = "Victims",
  ),
  ConditionMetadata(
    id = "ATTENDDEPENDENCYINDRUGSSECTION",
    text = "Attend [INSERT APPOINTMENT TIME DATE AND ADDRESS], as directed, to address your dependency on, or propensity to misuse, a controlled drug.",
    userInput = "appointmentDetailsInDrugsSection",
    fieldPosition = mapOf("appointmentDateInDrugsSection" to 0, "appointmentTimeInDrugsSection" to 1, "appointmentAddressInDrugsSection" to 2),
    groupName = "Drugs, health and behaviour",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "COMPLYREQUIREMENTS",
    text = "To comply with any requirements specified by your supervising officer for the purpose of ensuring that you address your [alcohol abuse / drug abuse / sexual behaviour / violent behaviour / gambling / solvent abuse / anger / debt / prolific behaviour/ offending behaviour] problems at the [NAME OF COURSE / CENTRE].",
    userInput = "courseOrCentre",
    fieldPosition = mapOf("abuseAndBehaviours" to 0, "courseOrCentre" to 1),
    groupName = "Drugs, health and behaviour",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ATTENDALL",
    text = "Attend all appointments arranged for you with [INSERT NAME], a [PSYCHIATRIST / PSYCHOLOGIST / MEDICAL PRACTITIONER] and co-operate fully with any care or treatment they recommend.",
    userInput = "appointmentName",
    fieldPosition = mapOf("appointmentName" to 0, "appointmentProfession" to 1),
    groupName = "Drugs, health and behaviour",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "HOMEVISITS",
    text = "Receive home visits from [INSERT NAME] Mental Health Worker.",
    userInput = "mentalHealthName",
    fieldPosition = mapOf("mentalHealthName" to 0),
    groupName = "Drugs, health and behaviour",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "REMAINADDRESS",
    text = "Confine yourself to remain at [CURFEW ADDRESS] initially from [START OF CURFEW HOURS] until [END OF CURFEW HOURS] each day, and, thereafter, for such a period as may be reasonably notified to you by your supervising officer; and comply with such arrangements as may be reasonably put in place and notified to you by your supervising officer so as to allow for your whereabouts and your compliance with your curfew requirement be monitored [WHETHER BY ELECTRONIC MEANS INVOLVING YOUR WEARING AN ELECTRONIC TAG OR OTHERWISE].",
    userInput = "curfewDetails",
    fieldPosition = mapOf("curfewTo" to 2, "curfewFrom" to 1, "curfewAddress" to 0, "curfewTagRequired" to 3),
    groupName = "Curfew and reporting",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "CONFINEADDRESS",
    text = "Confine yourself to an address approved by your supervising officer between the hours of [TIME] and [TIME] daily unless otherwise authorised by your supervising officer.  This condition will be reviewed by your supervising officer on a [WEEKLY / MONTHLY / ETC] basis and may be amended or removed if it is felt that the level of risk that you present has reduced appropriately.",
    userInput = "confinedDetails",
    fieldPosition = mapOf("confinedTo" to 0, "confinedFrom" to 1, "confinedReviewFrequency" to 2),
    groupName = "Curfew and reporting",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "REPORTTO",
    text = "Report to staff at [NAME OF APPROVED PREMISES / POLICE STATION] at [TIME / DAILY], unless otherwise authorised by your supervising officer.  This condition will be reviewed by your supervising officer on a [WEEKLY / MONTHLY / ETC] basis and may be amended or removed if it is felt that the level of risk you present has reduced appropriately.",
    userInput = "reportingDetails",
    fieldPosition = mapOf("reportingTime" to 1, "reportingDaily" to 2, "reportingAddress" to 0, "reportingFrequency" to 3),
    groupName = "Curfew and reporting",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "RETURNTOUK",
    text = "Should you return to the UK and Islands before the expiry date of your licence then your licence conditions will be in force and you must report within two working days to  our supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Travel",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NOTIFYPASSPORT",
    text = "To notify your supervising officer of the details of any passport that you possess (including passport number), and of any intention to apply for a new passport.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Travel",
    subgroupName = "Passports",
  ),
  ConditionMetadata(
    id = "SURRENDERPASSPORT",
    text = "To surrender your passport(s) to your supervising officer and to notify your supervising officer of any intention to apply for a new passport.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Travel",
    subgroupName = "Passports",
  ),
  ConditionMetadata(
    id = "VEHICLEDETAILS",
    text = "Provide your supervising officer with details [SUCH AS MAKE, MODEL, COLOUR, REGISTRATION] of any vehicle you own, hire for more than a short journey or have regular use of, prior to any journey taking place.",
    userInput = "vehicleDetails",
    fieldPosition = mapOf("vehicleDetails" to 0),
    groupName = "Travel",
    subgroupName = "Vehicles",
  ),
  ConditionMetadata(
    id = "EXCLUSIONADDRESS",
    text = "Not to enter [NAME/TYPE OF PREMISES / ADDRESS / ROAD] without the prior approval of your supervising officer.",
    userInput = "noEnterPlace",
    fieldPosition = mapOf("noEnterPlace" to 0),
    groupName = "Exclusion",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "EXCLUSIONAREA",
    text = "Not to enter the area of [CLEARLY SPECIFIED AREA], as defined by the attached map without the prior approval of your supervising officer.",
    userInput = "exclusionArea",
    fieldPosition = mapOf("exclusionArea" to 0),
    groupName = "Exclusion",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ONEPHONE",
    text = "Not to own or possess more than one mobile phone or SIM card without the prior approval of your supervising officer and to provide your supervising officer with details of that mobile telephone, including the IMEI number and the SIM card that you possess.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Technology",
    subgroupName = "Mobile phones",
  ),
  ConditionMetadata(
    id = "NOINTERNET",
    text = "Not to use or access any computer or device which is internet enabled without the prior approval of your supervising officer; and only for the purpose, and only at a public location, as specified by that officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Technology",
    subgroupName = "Computers and internet",
  ),
  ConditionMetadata(
    id = "USAGEHISTORY",
    text = "Not to delete the usage history on any internet enabled device or computer used and to allow such items to be inspected as required by the police or your supervising officer. Such inspection may include removal of the device for inspection and the installation of monitoring software.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Technology",
    subgroupName = "Computers and internet",
  ),
  ConditionMetadata(
    id = "NOCAMERA",
    text = "To make any device capable of making or storing digital images (including a camera and a mobile phone with a camera function) available for inspection on request by your supervising officer and/or a police officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Technology",
    subgroupName = "Cameras and photos",
  ),
  ConditionMetadata(
    id = "CAMERAAPPROVAL",
    text = "Not to own or use a camera without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Technology",
    subgroupName = "Cameras and photos",
  ),
  ConditionMetadata(
    id = "NOCAMERAPHONE",
    text = "Not to own or possess a mobile phone with a photographic function without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Technology",
    subgroupName = "Cameras and photos",
  ),
  ConditionMetadata(
    id = "POLYGRAPH",
    text = "To comply with any instruction given by your supervising officer requiring you to attend polygraph testing. To participate in polygraph sessions and examinations as instructed by or under the authority of your supervising officer and to comply with any instruction given to you during a polygraph session by the person conducting the polygraph.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Restricted additional conditions",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "DRUG_TESTING",
    text = "Attend [INSERT NAME AND ADDRESS], as reasonably required by your supervising officer, to give a sample of oral fluid / urine in order to test whether you have any specified Class A and specified Class B drugs in your body, for the purpose of ensuring that you are complying with the condition of your licence requiring you to be of good behaviour. Not to take any action that could hamper or frustrate the drug testing process.",
    userInput = "drug_testing",
    fieldPosition = mapOf("drug_testing_name" to 0, "drug_testing_address" to 1),
    groupName = "Restricted additional conditions",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ATTENDSAMPLE",
    text = "Attend [INSERT APPOINTMENT NAME AND ADDRESS], as reasonably required by your supervisor, to give a sample of oral fluid/urine in order to test whether you have any specified Class A and specified Class B drugs in your body, for the purpose of ensuring that you are complying with the requirement of supervision period requiring you to be of good behaviour.",
    userInput = "attendSampleDetails",
    fieldPosition = mapOf("attendSampleDetailsName" to 0, "attendSampleDetailsAddress" to 1),
    groupName = "Post-sentence supervision only",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ATTENDDEPENDENCY",
    text = "Attend [INSERT APPOINTMENT TIME DATE AND ADDRESS], as directed, to address your dependency on, or propensity to misuse, a controlled drug.",
    userInput = "appointmentDetails",
    fieldPosition = mapOf("appointmentDate" to 0, "appointmentTime" to 1, "appointmentAddress" to 2),
    groupName = "Post-sentence supervision only",
    subgroupName = null,
  ),
)
