package uk.gov.justice.digital.hmpps.hmppshdcapi.licences.conditions

// NOTE: DO NOT EDIT DIRECTLY: This is generated via "npm run generate:kotlin-types" in https://github.com/ministryofjustice/licences
 
val V2_CONDITIONS = listOf(
  ConditionMetadata(
    id = "RESIDE_AT_SPECIFIC_PLACE",
    text = "You must reside within [INSERT REGION] while of no fixed abode, unless otherwise approved by your supervising officer.",
    userInput = "resideWithinRegion",
    fieldPosition = mapOf("region" to 0),
    groupName = "Residence at a specific place",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_RESIDE",
    text = "Not to reside (not even to stay for one night) in the same household as [ANY / ANY FEMALE / ANY MALE] child under the age of [INSERT AGE] without the prior approval of your supervising officer.",
    userInput = "notToReside",
    fieldPosition = mapOf("notResideWithAge" to 1, "notResideWithGender" to 0),
    groupName = "Restriction of residency",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ATTEND_ALL",
    text = "Attend all appointments arranged for you with a [PSYCHIATRIST / PSYCHOLOGIST / MEDICAL PRACTITIONER] and co-operate fully with any care or treatment they recommend.",
    userInput = "attendAll",
    fieldPosition = mapOf("appointmentProfessions" to 0),
    groupName = "Making or maintaining contact with a person",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "HOME_VISITS",
    text = "Receive home visits from [INSERT NAME] Mental Health Worker.",
    userInput = "mentalHealthName",
    fieldPosition = mapOf("mentalHealthName" to 0),
    groupName = "Making or maintaining contact with a person",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ATTEND_DEPENDENCY_IN_DRUGS_SECTION",
    text = "Attend [INSERT APPOINTMENT TIME DATE AND ADDRESS], as directed, to address your dependency on, or propensity to misuse, a controlled drug.",
    userInput = "appointmentDetailsInDrugsSection",
    fieldPosition = mapOf("appointmentDateInDrugsSection" to 0, "appointmentTimeInDrugsSection" to 1, "appointmentAddressInDrugsSection" to 2),
    groupName = "Making or maintaining contact with a person",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_COMMUNICATE_VICTIM",
    text = "Not to seek to approach or communicate with [INSERT NAME OF VICTIM AND / OR FAMILY MEMBERS] without the prior approval of your supervising officer and / or [INSERT NAME OF APPROPRIATE SOCIAL SERVICES DEPARTMENT].",
    userInput = "victimDetails",
    fieldPosition = mapOf("socialServicesDept" to 1, "victimFamilyMembers" to 0),
    groupName = "Making or maintaining contact with a person",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "RETURN_TO_UK",
    text = "Should you return to the UK and Islands before the expiry date of your licence then your licence conditions will be in force and you must report within two working days to our supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Making or maintaining contact with a person",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_UNSUPERVISED_CONTACT",
    text = "Not to have unsupervised contact with  [ANY / ANY FEMALE / ANY MALE] children under the age of [INSERT AGE] without the prior approval of your supervising officer and / or [INSERT NAME OF APPROPRIATE SOCIAL SERVICES DEPARTMENT] except where that contact is inadvertent and not reasonably avoidable in the course of lawful daily life.",
    userInput = "noUnsupervisedContact",
    fieldPosition = mapOf("unsupervisedContactAge" to 1, "unsupervisedContactGender" to 0, "unsupervisedContactSocial" to 2),
    groupName = "Making or maintaining contact with a person",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_CONTACT_NAMED",
    text = "Not to contact or associate with [NAMED OFFENDER(S) / NAMED INDIVIDUAL(S)] without the prior approval of your supervising officer.",
    userInput = "noContactOffenders",
    fieldPosition = mapOf("noContactOffenders" to 0),
    groupName = "Making or maintaining contact with a person",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_CONTACT_SEX_OFFENDER",
    text = "Not to contact or associate with a known sex offender other than when compelled by attendance at a Treatment Programme or when residing at Approved Premises without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Making or maintaining contact with a person",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_CONTACT_PRISONER",
    text = "Not to contact directly or indirectly any person who is a serving or remand prisoner or detained in State custody, without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Making or maintaining contact with a person",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_CONTACT_ASSOCIATE",
    text = "Not to associate with any person currently or formerly associated with [NAME OR DESCRIBE SPECIFIC GROUPS OR ORGANISATIONS] without the prior approval of your supervising officer.",
    userInput = "groupsOrOrganisations",
    fieldPosition = mapOf("groupsOrOrganisation" to 0),
    groupName = "Making or maintaining contact with a person",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "COMPLY_REQUIREMENTS",
    text = "To comply with any requirements specified by your supervising officer for the purpose of ensuring that you address your [alcohol / drug / sexual / violent / gambling / solvent abuse / anger / debt / prolific / offending behaviour] problems at the [NAME OF COURSE / CENTRE].",
    userInput = "courseOrCentreV2",
    fieldPosition = mapOf("abuseAndBehaviours" to 0, "courseOrCentre" to 1),
    groupName = "Participation in, or co-operation with, a programme or set of activities",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_WORK_WITH_AGE",
    text = "Not to undertake work or other organised activity which will involve a person under the age of [INSERT AGE], either on a paid or unpaid basis without the prior approval of your supervising officer.",
    userInput = "noWorkWithAge",
    fieldPosition = mapOf("noWorkWithAge" to 0),
    groupName = "Participation in, or co-operation with, a programme or set of activities",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ONE_PHONE",
    text = "Not to own or possess more than one mobile phone or SIM card without the prior approval of your supervising officer and to provide your supervising officer with details of that mobile telephone or one you have regular use of, including the IMEI number and the SIM card that you possess.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Possession, ownership, control or inspection of specified items or documents.",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_CAMERA_PHONE",
    text = "Not to own or possess a mobile phone with a photographic function without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Possession, ownership, control or inspection of specified items or documents.",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "CAMERA_APPROVAL",
    text = "Not to own or use a camera without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Possession, ownership, control or inspection of specified items or documents.",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_CAMERA",
    text = "To make any device capable of making or storing digital images (including a camera and a mobile phone with a camera function) available for inspection on request by your supervising officer and/or a police officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Possession, ownership, control or inspection of specified items or documents.",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "SURRENDER_PASSPORT",
    text = "To surrender your passport(s) to your supervising officer and to notify your supervising officer of any intention to apply for a new passport.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Possession, ownership, control or inspection of specified items or documents.",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_INTERNET",
    text = "Not to use or access any computer or device which is internet enabled without the prior approval of your supervising officer; and only for the purpose, and only at a specific location, as specified by that officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Possession, ownership, control or inspection of specified items or documents.",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "USAGE_HISTORY",
    text = "Not to delete the usage history on any internet enabled device or computer used and to allow such items to be inspected as required by the police or your supervising officer. Such inspection may include removal of the device for inspection and the installation of monitoring software.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Possession, ownership, control or inspection of specified items or documents.",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "SPECIFIC_ITEM",
    text = "Not to own or possess a [SPECIFIED ITEM] without the prior approval of your supervising officer.",
    userInput = "specificItem",
    fieldPosition = mapOf("specificItem" to 0),
    groupName = "Possession, ownership, control or inspection of specified items or documents.",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "VEHICLE_DETAILS",
    text = "Provide your supervising officer with details [SUCH AS MAKE, MODEL, COLOUR, REGISTRATION] of any vehicle you own, hire for more than a short journey or have regular use of, prior to any journey taking place.",
    userInput = "vehicleDetails",
    fieldPosition = mapOf("vehicleDetails" to 0),
    groupName = " Disclosure of information",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "INTIMATE_RELATIONSHIP",
    text = "Notify your supervising officer of any developing intimate relationships with [WOMEN / MEN / WOMEN OR MEN].",
    userInput = "intimateGender",
    fieldPosition = mapOf("intimateGender" to 0),
    groupName = " Disclosure of information",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NOTIFY_RELATIONSHIP",
    text = "Notify your supervising officer of any developing personal relationships, whether intimate or not, with any person you know or believe to be resident in a household containing children under the age of 18. This includes persons known to you prior to your time in custody with whom you are renewing or developing a personal relationship with.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = " Disclosure of information",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NOTIFY_PASSPORT",
    text = "To notify your supervising officer of the details of any passport that you possess (including passport number), and of any intention to apply for a new passport.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = " Disclosure of information",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NOTIFY_BANKING",
    text = "Provide your supervising officer with the details of any bank accounts to which you are a signatory and of any credit cards you possess. You must also notify your supervising officer when becoming a signatory to any new bank account or credit card, and provide the account/card details. This condition will be reviewed on a monthly basis and may be amended or removed if it is felt that the level of risk that you present has reduced appropriately.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = " Disclosure of information",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "CONFINE_ADDRESS",
    text = "Confine yourself to an address approved by your supervising officer between the hours of [TIME] and [TIME] daily unless otherwise authorised by your supervising officer.  This condition will be reviewed by your supervising officer on a [WEEKLY / MONTHLY / ETC] basis and may be amended or removed if it is felt that the level of risk that you present has reduced appropriately.",
    userInput = "confinedDetails",
    fieldPosition = mapOf("confinedTo" to 0, "confinedFrom" to 1, "confinedReviewFrequency" to 2),
    groupName = "Curfew arrangement",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "REMAIN_ADDRESS",
    text = "Confine yourself to remain at [CURFEW ADDRESS] initially from [START OF CURFEW HOURS] until [END OF CURFEW HOURS] each day, and, thereafter, for such a period as may be reasonably notified to you by your supervising officer; and comply with such arrangements as may be reasonably put in place and notified to you by your supervising officer so as to allow for your whereabouts and your compliance with your curfew requirement be monitored [WHETHER BY ELECTRONIC MEANS INVOLVING YOUR WEARING AN ELECTRONIC TAG OR OTHERWISE].",
    userInput = "curfewDetails",
    fieldPosition = mapOf("curfewTo" to 2, "curfewFrom" to 1, "curfewAddress" to 0, "curfewTagRequired" to 3),
    groupName = "Curfew arrangement",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "EXCLUSION_AREA",
    text = "Not to enter the area of [CLEARLY SPECIFIED AREA], as defined by the attached map without the prior approval of your supervising officer.",
    userInput = "exclusionArea",
    fieldPosition = mapOf("exclusionArea" to 0),
    groupName = "Freedom of movement",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "EXCLUSION_ADDRESS",
    text = "Not to enter [NAME/TYPE OF PREMISES / ADDRESS / ROAD] without the prior approval of your supervising officer.",
    userInput = "noEnterPlace",
    fieldPosition = mapOf("noEnterPlace" to 0),
    groupName = "Freedom of movement",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "NO_CHILDRENS_AREA",
    text = "Not to enter or remain in sight of any [CHILDREN’S PLAY AREA, SWIMMING BATHS, SCHOOL ETC] without the prior approval of your supervising officer.",
    userInput = "notInSightOf",
    fieldPosition = mapOf("notInSightOf" to 0),
    groupName = "Freedom of movement",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "POLICE_ESCORT",
    text = "On release to be escorted by police to Approved Premises.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Freedom of movement",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "PLACE_OF_WORSHIP",
    text = "To only attend places of worship which have been previously agreed with your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Freedom of movement",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "REPORT_TO",
    text = "Report to staff at [NAME OF APPROVED PREMISES / POLICE STATION] [at TIME / DAILY], unless otherwise authorised by your supervising officer.  This condition will be reviewed by your supervising officer on a [WEEKLY / MONTHLY / ETC] basis and may be amended or removed if it is felt that the level of risk you present has reduced appropriately.",
    userInput = "reportingDetailsV2",
    fieldPosition = mapOf("reportingTime" to 1, "reportingDaily" to 5, "reportingAddress" to 0, "reportingFrequency" to 2),
    groupName = "Supervision in the community by the supervising officer, or other responsible officer, or organisation",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "SPECIFIC_CONDUCT_OR_ACTS",
    text = "Not to participate directly or indirectly in organising and/or contributing to any demonstration, meeting, gathering or website without the prior approval of your supervising officer. This condition will be reviewed on a monthly basis and may be amended or removed if your risk is assessed as having changed.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Restriction of specified conduct or specified acts",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "CONTACT_EXTREME",
    text = "Not to contact directly or indirectly any person whom you know or believe to have been charged or convicted of any extremist related offence, without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Extremism",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ATTEND_EXTREME",
    text = "Not to attend or organise any meetings or gatherings other than those convened solely for the purposes of worship without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Extremism",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "DELIVER_EXTREME",
    text = "Not to give or engage in the delivery of any lecture, talk, or sermon whether part of an act of worship or not, without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Extremism",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "PROMOTE_EXTREME",
    text = "Not to engage in any discussion or act to promote grooming or influencing of an individual or a group for the purpose of extremism or radicalisation.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Extremism",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "EXTREME_MATERIALS",
    text = "Not to have in your possession any printed or electronically recorded material or handwritten notes which contain encoded information or that promote the destruction of or hatred for any religious or ethnic group or that celebrates, justifies or promotes acts of violence, or that contain information about military or paramilitary technology, weapons, techniques or tactics without the prior approval of your supervising officer.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Extremism",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ALLOW_POLICE_SEARCH",
    text = "You must let the police search you if they ask. You must also let them search a vehicle you are with, like a car or a motorbike.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Extremism",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "POLYGRAPH",
    text = "To comply with any instruction given by your supervising officer requiring you to attend polygraph testing. To participate in polygraph sessions and examinations as instructed by or under the authority of your supervising officer and to comply with any instruction given to you during a polygraph session by the person conducting the polygraph.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Polygraph Condition",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "DRUG_TESTING",
    text = "Attend [INSERT NAME AND ADDRESS], as reasonably required by your supervising officer, to give a sample of oral fluid / urine in order to test whether you have any specified Class A and specified Class B drugs in your body, for the purpose of ensuring that you are complying with the condition of your licence requiring you to be of good behaviour.",
    userInput = "drug_testing",
    fieldPosition = mapOf("drug_testing_name" to 0, "drug_testing_address" to 1),
    groupName = "Drug Testing Conditions",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "DONT_HAMPER_DRUG_TESTING",
    text = "Not to take any action that could hamper or frustrate the drug testing process.",
    userInput = "null",
    fieldPosition = emptyMap(),
    groupName = "Drug Testing Conditions",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ELECTRONIC_MONITORING_INSTALLATION",
    text = "Allow person(s) as designated by your supervising officer to install an electronic monitoring tag on you and access to install any associated equipment in your property, and for the purpose of ensuring that equipment is functioning correctly. You must not damage or tamper with these devices and ensure that the tag is charged, and report to your supervising officer and the EM provider immediately if the tag or the associated equipment are not working correctly. This will be for the purpose of monitoring your [INSERT TYPES OF CONDITIONS TO BE ELECTRONICALLY MONITORED HERE] licence condition(s) unless otherwise authorised by your supervising officer.",
    userInput = "electronicMonitoringInstallation",
    fieldPosition = mapOf("conditionTypes" to 0),
    groupName = "Electronic Monitoring Conditions",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ELECTRONIC_MONITORING_TRAIL",
    text = "You will be subject to trail monitoring. Your whereabouts will be electronically monitored by GPS Satellite Tagging, ending on [INSERT END DATE], and you must cooperate with the monitoring as directed by your supervising officer unless otherwise authorised by your supervising officer.",
    userInput = "electronicTrailMonitoring",
    fieldPosition = mapOf("trailEndDate" to 0),
    groupName = "Electronic Monitoring Conditions",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "CURFEW_UNTIL_INSTALLATION",
    text = "You must stay at [APPROVED ADDRESS] between 5pm and midnight every day until your electronic tag is installed unless otherwise authorised by your supervising officer.",
    userInput = "curfewUntilInstallation",
    fieldPosition = mapOf("approvedAddress" to 0),
    groupName = "Electronic Monitoring Conditions",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ALCOHOL_MONITORING",
    text = "You are subject to alcohol monitoring. Your alcohol intake will be electronically monitoring for a period of [INSERT TIMEFRAME AND END DATE], and you may not consume units of alcohol, unless otherwise permitted by your supervising officer.",
    userInput = "alcoholMonitoring",
    fieldPosition = mapOf("timeframe" to 0, "endDate" to 1),
    groupName = "Electronic Monitoring Conditions",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ATTEND_SAMPLE",
    text = "Attend [INSERT APPOINTMENT NAME AND ADDRESS], as reasonably required by your supervisor, to give a sample of oral fluid/urine in order to test whether you have any specified Class A and specified Class B drugs in your body, for the purpose of ensuring that you are complying with the requirement of supervision period requiring you to be of good behaviour.",
    userInput = "attendSampleDetails",
    fieldPosition = mapOf("attendSampleDetailsName" to 0, "attendSampleDetailsAddress" to 1),
    groupName = "Post-sentence supervision only",
    subgroupName = null,
  ),
  ConditionMetadata(
    id = "ATTEND_DEPENDENCY",
    text = "Attend [INSERT APPOINTMENT TIME DATE AND ADDRESS], as directed, to address your dependency on, or propensity to misuse, a controlled drug.",
    userInput = "appointmentDetails",
    fieldPosition = mapOf("appointmentDate" to 0, "appointmentTime" to 1, "appointmentAddress" to 2),
    groupName = "Post-sentence supervision only",
    subgroupName = null,
  ),
)
