apiVersion: batch/v1
kind: CronJob
metadata:
  name: reset-licences
spec:
  schedule: "{{ .Values.cron.resetLicences }}"
  concurrencyPolicy: Replace
  failedJobsHistoryLimit: 5
  startingDeadlineSeconds: 43200
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 345600 # 4 days
      backoffLimit: 2
      template:
        spec:
          restartPolicy: Never
          activeDeadlineSeconds: 3600
          containers:
            - name: reset-licences-job
              image: ghcr.io/ministryofjustice/hmpps-devops-tools
              args:
                - /bin/sh
                - -c
                - curl --fail --retry 2 -X POST "https://$BASE_URL/jobs/delete-inactive-licences/500"
              env:
                - name: BASE_URL
                  value: {{ index .Values "generic-service" "ingress" "host" }}
