---
# Per environment values which override defaults in hmpps-hdc-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: hdc-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HMPPS_AUTH_TOKEN_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth/oauth/token"
    HMPPS_PRISON_API_URL: "https://prison-api-dev.prison.service.justice.gov.uk/api"
    HMPPS_PRISONERSEARCH_API_URL: "https://prisoner-search-dev.prison.service.justice.gov.uk"

  retryDlqCronjob:
    enabled: true
  scheduledDowntime:
    enabled: true

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: cvl-alerts-non-prod
  businessHoursOnly: true
  rdsAlertsDatabases:
    cloud-platform-d8898a26211073bc: "HDC"
  sqsAlertsQueueNames:
    - "Digital-Prison-Services-dev-hdc_domain_events_queue"
    - "Digital-Prison-Services-dev-hdc_domain_events_dl"
cron:
  resetLicences:
    enabled: true
    schedule: "30 7 * * 1-5"
